package com.mykaarma.test.client.config;

public enum MongoCollections {

	DMSROXML,DMSAPPOINTMENTXML,DMSCUSTOMERXML,DMSVEHICLEXML,DMSPARTSXML,PDF,TESTXML,KAARMADEALERORDER,KAARMACUSTOMER,KAARMAVEHICLE,KAARMASERVICEAPPOINTMENTREQUEST,KAARMAPARTSORDER
}
